# Generated by Django 4.2 on 2023-04-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionoptions",
            old_name="title",
            new_name="option",
        ),
    ]
