# Generated by Django 4.2 on 2023-04-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_vote_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
